name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: read
    environment: ci

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: setup gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: print environment
      run: echo "CI_ENV=${{ ci.CI_ENV }}, TEST_SECRET=${{ ci.TEST_SECRET }}"

    - name: increment project version
      run: ./gradlew release-paperwork

    - name: build gradle distributions
      run: ./gradlew buildGradleDist

    - name: build documentation jar
      run: ./gradlew docJar

    - name: publish to maven central
#      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      run: echo "dummy publish step"
