name: Java CI with Gradle

on:
  push:
#    TODO remove unnecessary whitespaces
    branches: [  "main" ]

jobs:
  build:
    uses: harmonysoft-tech/ci/.github/workflows/library-gradle-release.yml@main
    secrets: inherit
    permissions:
      contents: write